const projects = [
    {
        "name": "Prosjekt",
        "units": 0,
        "sold": 0,
        "price_from": 0,
        "link": "",
        "description": "Salgsstart: Ukjent",
        "completion_text": "Ukjent",
        "active": false,
        "area": "Oslo"
    },
    {
        "name": "\u00c5sjordet 3",
        "units": 19,
        "sold": 9,
        "price_from": 13968421,
        "link": "https://www.finn.no/realestate/newbuildings/search.html?q=%C3%85sjordet+3",
        "description": "Salgsstart: 2. kvartal 2027",
        "completion_text": "2. kvartal 2027",
        "active": false,
        "area": "Oslo"
    },
    {
        "name": "Fagerblom",
        "units": 82,
        "sold": 52,
        "price_from": 10994146,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=414884916",
        "description": "Salgsstart: 4. kvartal 2027 (sep\u2013des)",
        "completion_text": "4. kvartal 2027 (sep\u2013des)",
        "active": false,
        "area": "Oslo"
    },
    {
        "name": "Fryd",
        "units": 62,
        "sold": 42,
        "price_from": 7858064,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=424058560",
        "description": "Salgsstart: 1. halv\u00e5r 2028 (estimert)",
        "completion_text": "1. halv\u00e5r 2028 (estimert)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Frysjatunet",
        "units": 26,
        "sold": 12,
        "price_from": 9340400,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=354646499",
        "description": "Salgsstart: Fra 4. kvartal 2027 (planlagt)",
        "completion_text": "Fra 4. kvartal 2027 (planlagt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Frysjatunet",
        "units": 10,
        "sold": 3,
        "price_from": 18150000,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=354646499",
        "description": "Salgsstart: Fra 4. kvartal 2027 (planlagt)",
        "completion_text": "Fra 4. kvartal 2027 (planlagt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Furuset Village",
        "units": 16,
        "sold": 2,
        "price_from": 5399333,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=436640537",
        "description": "Salgsstart: Fra 2. kvartal 2027 (planlagt)",
        "completion_text": "Fra 2. kvartal 2027 (planlagt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Granstangen Park",
        "units": 44,
        "sold": 26,
        "price_from": 6772954,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=445233552",
        "description": "Salgsstart: 3. kvartal 2027",
        "completion_text": "3. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Granstangen Park",
        "units": 27,
        "sold": 8,
        "price_from": 5497407,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=445233552",
        "description": "Salgsstart: 3. kvartal 2027",
        "completion_text": "3. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Gr\u00f8nvollkvartalet",
        "units": 70,
        "sold": 45,
        "price_from": 8292214,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=381077268",
        "description": "Salgsstart: 2. kvartal 2028",
        "completion_text": "2. kvartal 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Haslevangen",
        "units": 36,
        "sold": 28,
        "price_from": 9431944,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=406343945",
        "description": "Salgsstart: 1. halv\u00e5r 2027",
        "completion_text": "1. halv\u00e5r 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Haslevangen",
        "units": 43,
        "sold": 29,
        "price_from": 7775000,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=406343945",
        "description": "Salgsstart: 1. halv\u00e5r 2027",
        "completion_text": "1. halv\u00e5r 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Haslevangen",
        "units": 27,
        "sold": 7,
        "price_from": 7863461,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=406343945",
        "description": "Salgsstart: 1. halv\u00e5r 2027",
        "completion_text": "1. halv\u00e5r 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Holtet Hage",
        "units": 13,
        "sold": 13,
        "price_from": 16769230,
        "link": "",
        "description": "Salgsstart: Ikke oppgitt (prosjektet fremst\u00e5r ferdigstilt/solgt)",
        "completion_text": "Ikke oppgitt (prosjektet fremst\u00e5r ferdigstilt/solgt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Kampenhagen",
        "units": 100,
        "sold": 79,
        "price_from": 9095200,
        "link": "https://www.finn.no/realestate/projectsingle/ad.html?finnkode=442556154",
        "description": "Salgsstart: 1. halv\u00e5r 2028",
        "completion_text": "1. halv\u00e5r 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Konows Hager",
        "units": 19,
        "sold": 7,
        "price_from": 10613157,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=405781299",
        "description": "Salgsstart: 2. kvartal 2028",
        "completion_text": "2. kvartal 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Landingsveien 14",
        "units": 56,
        "sold": 46,
        "price_from": 6206583,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=419896586",
        "description": "Salgsstart: 3./4. kvartal 2027",
        "completion_text": "3./4. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Lenschows",
        "units": 70,
        "sold": 45,
        "price_from": 9095000,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=409114246",
        "description": "Salgsstart: 2. halv\u00e5r 2028",
        "completion_text": "2. halv\u00e5r 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Lenschows",
        "units": 42,
        "sold": 15,
        "price_from": 8351190,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=409114246",
        "description": "Salgsstart: 2. halv\u00e5r 2028",
        "completion_text": "2. halv\u00e5r 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Libakkl\u00f8kka",
        "units": 58,
        "sold": 40,
        "price_from": 6815344,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=402435560",
        "description": "Salgsstart: 3. kvartal 2027",
        "completion_text": "3. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Linderudl\u00f8kka",
        "units": 71,
        "sold": 52,
        "price_from": 6027887,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=423953355",
        "description": "Salgsstart: 2. halv\u00e5r 2028",
        "completion_text": "2. halv\u00e5r 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Linderudl\u00f8kka",
        "units": 73,
        "sold": 29,
        "price_from": 6073972,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=423953355",
        "description": "Salgsstart: 2. halv\u00e5r 2028",
        "completion_text": "2. halv\u00e5r 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Mariakvartalet",
        "units": 38,
        "sold": 11,
        "price_from": 14053947,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=330783701",
        "description": "Salgsstart: 4. kvartal 2026 / 1. kvartal 2027",
        "completion_text": "4. kvartal 2026 / 1. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Oen",
        "units": 46,
        "sold": 23,
        "price_from": 6332608,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=407946053",
        "description": "Salgsstart: Fra 2. kvartal 2027 (planlagt)",
        "completion_text": "Fra 2. kvartal 2027 (planlagt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Oen",
        "units": 49,
        "sold": 6,
        "price_from": 8163541,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=407946053",
        "description": "Salgsstart: Fra 2. kvartal 2027 (planlagt)",
        "completion_text": "Fra 2. kvartal 2027 (planlagt)",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Over Torshov",
        "units": 35,
        "sold": 28,
        "price_from": 7561470,
        "link": "https://www.finn.no/realestate/homes/ad.html?finnkode=446237655",
        "description": "Salgsstart: 1. kvartal 2027",
        "completion_text": "1. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Staffeldts gate 2",
        "units": 38,
        "sold": 34,
        "price_from": 7818055,
        "link": "",
        "description": "Salgsstart: Ukjent",
        "completion_text": "Ukjent",
        "active": false,
        "area": "Oslo"
    },
    {
        "name": "Stovner Torg",
        "units": 88,
        "sold": 51,
        "price_from": 4790397,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=436825628",
        "description": "Salgsstart: 1. kvartal 2028",
        "completion_text": "1. kvartal 2028",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Ullernh\u00f8yden",
        "units": 30,
        "sold": 16,
        "price_from": 10781666,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=409940269",
        "description": "Salgsstart: 2. kvartal 2027",
        "completion_text": "2. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Ulvenplassen",
        "units": 73,
        "sold": 45,
        "price_from": 6573972,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=269266543",
        "description": "Salgsstart: 15.01.2026\u201315.04.2026",
        "completion_text": "15.01.2026\u201315.04.2026",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Ulvenplassen",
        "units": 62,
        "sold": 11,
        "price_from": 6451612,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=269266543",
        "description": "Salgsstart: 15.01.2026\u201315.04.2026",
        "completion_text": "15.01.2026\u201315.04.2026",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Ulvenplassen",
        "units": 55,
        "sold": 17,
        "price_from": 7078181,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=269266543",
        "description": "Salgsstart: 15.01.2026\u201315.04.2026",
        "completion_text": "15.01.2026\u201315.04.2026",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Ulvenplassen",
        "units": 56,
        "sold": 14,
        "price_from": 7231250,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=269266543",
        "description": "Salgsstart: 15.01.2026\u201315.04.2026",
        "completion_text": "15.01.2026\u201315.04.2026",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Vester\u00e5sveien Panorama",
        "units": 10,
        "sold": 4,
        "price_from": 21922222,
        "link": "https://www.finn.no/realestate/project/ad.html?finnkode=412361233",
        "description": "Salgsstart: 2. kvartal 2027",
        "completion_text": "2. kvartal 2027",
        "active": true,
        "area": "Oslo"
    },
    {
        "name": "Villa Silur",
        "units": 53,
        "sold": 34,
        "price_from": 10763207,
        "link": "https://www.finn.no/realestate/projectunit/ad.html?finnkode=393490306",
        "description": "Salgsstart: Sommeren 2027",
        "completion_text": "Sommeren 2027",
        "active": true,
        "area": "Oslo"
    },

];

export default projects;